AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provide basic urban dictionary lookup functionality
Resources:
  urbanDictionarySkill:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Provide basic urban dictionary lookup functionality
      MemorySize: 128
      Timeout: 7
      Role: 'arn:aws:iam::977866846585:role/lambda_basic_execution'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Tags:
        'lambda-console:blueprint': urban-dictionary-skill
